Description of testFileExistence
Home > OpenBDLM_V1.0 > functions > Others > testFileExistence.m
testFileExistence
PURPOSE
TESTFILEEXISTENCE Test existence of a file
SYNOPSIS
function [isFileExist]=testFileExistence(FileName, FileType)
DESCRIPTION
TESTFILEEXISTENCE Test existence of a file
   SYNOPSIS:
     [isExist]=TESTFILEEXISTENCE(FilePath, FileType)
   INPUT:
      FileName - character (required)
                 Indicate absolute path of the file
      FileType - character (required)
                 Indicate the file type, is either 'file' or 'dir'
   OUTPUT:
      isExist  - logical
                 if isExist = true , the file exists in the specified
                 FilePath
   DESCRIPTION:
      TESTFILEEXISTENCE tests existence of a file given in FileName
      Important: the absolute path of FileName should be specified.
   EXAMPLES:
      [isExist]=TESTFILEEXISTENCE('./home/saved_projects', 'dir')
      [isExist]=TESTFILEEXISTENCE('./home/test.m', 'file')
   See also
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
displayDataBinary DISPLAYDATABINARY Display the list of DATA_*.mat files
readSingleCSVFile READSINGLECSVFILE Read a single OpenBDLM CSV data file
readSingleMATFile READSINGLEMATFILE Read a single OpenBDLM MAT data file
Clean CLEAN Clean OpenBDLM folder tree
chooseProjectName CHOOSEPROJECTNAME Request user's input to choose a project name
convertMAT2CSV CONVERTMAT2CSV Convert a OpenBDLM DATA_*.mat file to OpenBDLM CSV file(s)
createLogFile CREATELOGFILE Create log file to print message during program execution
displayProjects DISPLAYPROJECTS displays on screen information about saved projects
printConfigurationFile PRINTCONFIGURATIONFILE Create and print a configuration file from project
saveDataBinary SAVEDATABINARY Save data in a binary Matlab .mat file
saveDataCSV SAVEDATACSV Save time series data in separate .csv files
saveProject SAVEPROJECT Save the variables model, estimation, misc in a .mat file
saveResultsCSV SAVERESULTSCSV Save results in CSV files
saveResultsMAT SAVERESULTSMAT Save results in a .mat file
setInternalVars SETINTERNALVARS Read OpenBDLM arguments and set internal variables
exportPlot EXPORTPLOT Export the current figure in TeX file using matlab2tikz
plotData PLOTDATA Plot data amplitude values and data timestep
plotDataAvailability PLOTDATAAVAILABILITY Summarize data availability of a time series dataset
plotDataSummary PLOTDATASUMMARY Plot data amplitude, data time step, and data availability
plotDataTimestep PLOTDATATIMESTEP Plot data timestep vector
plotEstimations PLOTESTIMATIONS Plot hidden states, predicted data, and model probability
plotHiddenStates PLOTHIDDENSTATES Plot true and estimated hidden states
plotKernelRegression PLOTKERNELREGRESSION Plot Kernel regression time series pattern
plotModelProbability PLOTMODELPROBABILITY Plot true and estimated model probability
plotPredictedData PLOTPREDICTEDDATA Plot observed and predicted data
plotWaterfallKRegression PLOTWATERFALLKREGRESSION Waterfall plot for kernel regression component
SOURCE CODE
function [isFileExist]=testFileExistence(FileName, FileType)
%TESTFILEEXISTENCE Test existence of a file
%
%   SYNOPSIS:
%     [isExist]=TESTFILEEXISTENCE(FilePath, FileType)
%
%   INPUT:
%      FileName - character (required)
%                 Indicate absolute path of the file
%
%      FileType - character (required)
%                 Indicate the file type, is either 'file' or 'dir'
%
%   OUTPUT:
%      isExist  - logical
%                 if isExist = true , the file exists in the specified
%                 FilePath
%
%   DESCRIPTION:
%      TESTFILEEXISTENCE tests existence of a file given in FileName
%      Important: the absolute path of FileName should be specified.
%
%   EXAMPLES:
%      [isExist]=TESTFILEEXISTENCE('./home/saved_projects', 'dir')
%      [isExist]=TESTFILEEXISTENCE('./home/test.m', 'file')
%
%   See also
%   AUTHORS:
%      Ianis Gaudot
%
%   MATLAB VERSION:
%      Tested on 9.1.0.441655 (R2016b)
%
%   DATE CREATED:
%       April 24, 2018
%
%   DATE LAST UPDATE:
%       April 24, 2018
%--------------------BEGIN CODE ----------------------
%% Get arguments passed to the function and proceed to some verifications
p = inputParser;
validationFct_FileName = @(x) ischar(x) && ...
    ~isempty(x(~isspace(x)));
validationFct_Type = @(x) (ischar(x) && ...
    ~isempty(x(~isspace(x)))) && ...
    (strcmp(x, 'file') || strcmp(x, 'dir'));
addRequired(p, 'FileName', validationFct_FileName)
addRequired(p, 'FileType', validationFct_Type)
parse(p,FileName, FileType);
FileName=p.Results.FileName;
FileType=p.Results.FileType;
%% Convert relative to absolute path
if isempty(strfind(FileName, '/')) && isempty(strfind(FileName, '\'))
    FileName=fullfile(pwd, FileName);
end
%% Verify presence of the file
if strcmp(FileType, 'file')
    if exist(FileName, FileType) == 2
       isFileExist = true;
    else
       isFileExist = false ;
    end
elseif strcmp(FileType, 'dir')
    if exist(FileName, FileType) == 7
       isFileExist = true;
    else
       isFileExist = false ;
    end
end
%--------------------END CODE ------------------------
end