Description of computeTimeSteps
Home > OpenBDLM_V1.0 > functions > DataLoader > computeTimeSteps.m
computeTimeSteps
PURPOSE
COMPUTETIMESTEPS Compute timestep vector from timestamps vector
SYNOPSIS
function [timesteps]=computeTimeSteps(timestamps)
DESCRIPTION
COMPUTETIMESTEPS Compute timestep vector from timestamps vector
   SYNOPSIS:
     [timestep]=COMPUTETIMESTEPS(timestamps)
   INPUT:
      timestamps                 - Mx1 real array (required)
                                   timestamp vector
                                   M: number of samples in the time series
   OUTPUT:
      timesteps                  - (M-1)x1 real array (required)
                                   timestep vector
                                   M: number of samples in the time series
   DESCRIPTION:
      COMPUTETIMESTEPS compute timestep vector from timestamps vector
   EXAMPLES:
      [timesteps]=COMPUTETIMESTEPS(timestamps)
   See also DISPLAYMODELMATRICES
CROSS-REFERENCE INFORMATION
This function calls:
defineReferenceTimeStep DEFINEREFERENCETIMESTEP Compute reference timestep of a timestamp vector
This function is called by:
simulateDataFromCustomAnomalies SIMULATEDATAFROMCUSTOMANOMALIES Create synth. data from custom anomalies
simulateDataFromTransitionProbabilities SIMULATEDATAFROMTRANSITIONPROBABILITIES Create synth. data from trans. prob.
NewtonRaphson NEWTONRAPHSON Learn models parameters using the Newton-Raphson technique
displayModelMatrices DISPLAYMODELMATRICES Display A,C, Q, R matrices for a given timestamp
RTS_SwitchingKalmanSmoother RTS_SWITCHINGKALMANSMOOTHER Perform RTS Switching Kalman smoothing
StateEstimation STATEESTIMATION State estimation from switching Kalman filtering/smoothing
SwitchingKalmanFilter SWITCHINGKALMANFILTER Perform Switching Kalman filtering of time series
plotData PLOTDATA Plot data amplitude values and data timestep
plotDataSummary PLOTDATASUMMARY Plot data amplitude, data time step, and data availability
plotDataTimestep PLOTDATATIMESTEP Plot data timestep vector
plotKernelRegression PLOTKERNELREGRESSION Plot Kernel regression time series pattern
plotPredictedData PLOTPREDICTEDDATA Plot observed and predicted data
SOURCE CODE
function [timesteps]=computeTimeSteps(timestamps)
%COMPUTETIMESTEPS Compute timestep vector from timestamps vector
%
%   SYNOPSIS:
%     [timestep]=COMPUTETIMESTEPS(timestamps)
%
%   INPUT:
%      timestamps                 - Mx1 real array (required)
%                                   timestamp vector
%                                   M: number of samples in the time series
%
%   OUTPUT:
%      timesteps                  - (M-1)x1 real array (required)
%                                   timestep vector
%                                   M: number of samples in the time series
%
%   DESCRIPTION:
%      COMPUTETIMESTEPS compute timestep vector from timestamps vector
%
%   EXAMPLES:
%      [timesteps]=COMPUTETIMESTEPS(timestamps)
%
%   See also DISPLAYMODELMATRICES
%   AUTHORS:
%      James-A Goulet, Luong Ha Nguyen, Ianis Gaudot
%
%      Email: <james.goulet@polymtl.ca>
%      Website: <http://www.polymtl.ca/expertises/goulet-james-alexandre>
%
%   MATLAB VERSION:
%      Tested on 9.1.0.441655 (R2016b)
%
%   DATE CREATED:
%       April 24, 2018
%
%   DATE LAST UPDATE:
%       July 24, 2018
%--------------------BEGIN CODE ----------------------
%% Get arguments passed to the function and proceed to some verifications
p = inputParser;
ValidationFcn = @(x)isnumeric(x)&~isempty(x)&length(x)>2;
addRequired(p,'timestamps', ValidationFcn);
parse(p,timestamps);
%% Compute timestep vector
[referencetimestep]=defineReferenceTimeStep(timestamps);
timesteps = [referencetimestep; diff(timestamps)];
%--------------------END CODE ------------------------
end