%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                         %
%                                                                         %
%                    OpenBDLM configuration file                          %
%          Autogenerated by OpenBDLM on 10-Aug-2018 06:58:45              %
%                                                                         %
%                                                                         %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% A - Project name
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
misc.ProjectName='DEMO';

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% B - Data
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
dat=load('DATA_DEMO.mat'); 
data.values=dat.values;
data.timestamps=dat.timestamps;
misc.trainingPeriod=[1,1096];
data.labels={'TS01'};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% C - Model structure 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Components reference numbers
% 11: Local level
% 12: Local trend
% 13: Local acceleration
% 21: Local level compatible with local trend
% 22: Local level compatible with local acceleration
% 23: Local trend compatible with local acceleration
% 31: Periodic
% 41: Autoregressive
% 51: Dynamic regression with hidden component
% 52: Static kernel regression
% 53: Dynamic kernel regression
% 61: Level Intervention

% Model components
% Model 1
model.components.block{1}={[12 31 31 31 52 41 ] };

% Model component constrains | Take the same  parameter as model class #1
 
% Model inter-components dependence | {[components form dataset_i depends on components from  dataset_j]_i,[...]}
model.components.ic={[ ] };

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% D - Model parameters 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
model.param_properties={
    % #1             #2         #3       #4      #5                  #6          #7      #8      #9              #10
    % Param name     Block name Model    Obs     Bound               Prior       Mean    Std     Values          Ref
	'\sigma_w'  ,	 'LT',		'1',	 '1',	 [ 0    , Inf  ],	 'normal',	 0 ,	 1E+06,	 1E-07   ,  	 1  %#1
	'p'         ,	 'PD1',		'1',	 '1',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 365.24  ,  	 2  %#2
	'\sigma_w'  ,	 'PD1',		'1',	 '1',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 0       ,  	 3  %#3
	'p'         ,	 'PD2',		'1',	 '1',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 1       ,  	 4  %#4
	'\sigma_w'  ,	 'PD2',		'1',	 '1',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 0       ,  	 5  %#5
	'p'         ,	 'PD3',		'1',	 '1',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 182.62  ,  	 6  %#6
	'\sigma_w'  ,	 'PD3',		'1',	 '1',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 0       ,  	 7  %#7
	'\sigma_w'  ,	 'SK',		'1',	 '1',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 0       ,  	 8  %#8
	'\ell'      ,	 'SK',		'1',	 '1',	 [ 0    , Inf  ],	 'normal',	 0 ,	 1E+06,	 0.5     ,  	 9  %#9
	'p'         ,	 'SK',		'1',	 '1',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 365.24  ,  	 10 %#10
	'\phi'      ,	 'AR',		'1',	 '1',	 [ 0    , 1    ],	 'normal',	 0 ,	 1E+06,	 0.75    ,  	 11 %#11
	'\sigma_w'  ,	 'AR',		'1',	 '1',	 [ 0    , Inf  ],	 'normal',	 0 ,	 1E+06,	 0.01    ,  	 12 %#12
	'\sigma_v'  ,	 '',		'1',	 '1',	 [ 0    , Inf  ],	 'normal',	 0 ,	 1E+06,	 0.01    ,  	 13 %#13
};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% E - Initial states values 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Initial hidden states mean for model 1:
model.initX{ 1 }=[	10    	-0.1  	10    	10    	10    	10    	10    	10    	2.01  	2.02  	1.29  	0.153 	-0.775	-0.956	-0.297	0.793 	1.68  	1.92  	1.55  	0.991 	0.747 	1.01  	1.52  	1.74  	1.28  	0.171 	-1.09 	-1.87 	-1.77 	-0.958	0.0325	0.598 	0.486 	-0.0775	-0.578	-0.61 	-0.181	0.294 	0.288 	-0.434	-1.62 	-2.66 	-2.98 	-2.42 	-1.33 	-0.334	0.0785	-0.138	-0.592	-0.769	-0.421	0.246 	0.719 	0.552 	-0.289	-1.36 	-2.02 	-1.84 	0     ]';

% Initial hidden states variance for model 1: 
model.initV{ 1 }=diag([ 	0.01  	0.01  	0.04  	0.04  	0.04  	0.04  	0.04  	0.04  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01  	0.01   ]);

% Initial probability for model 1
model.initS{1}=[1     ];

