%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                    OpenBDLM configuration file                          %
%          Autogenerated by OpenBDLM on 14-Aug-2018 16:50:06              %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% A - Project name
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
misc.ProjectName='PJCCI_1_SKF_KR';

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% B - Data
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
load('May_2018_Test_56_data_real_6yeasr_7days_PJCCJ.mat'); 

iNdex1 = 1;%find(data_7days.timestamps==733043); % Begining of the data 2007,01,01,00,00,00
% Important: once you use 2days 734504 is changed to 734503
% Important: once you use 7days 734504 is changed to 734499
% Important: once you use 7days 735235 is changed to 735234
iNdex2 = 314;%find(data_7days.timestamps==734139); % 2008=733408 and 2009 = 733774 and 2010= 734139 and 2011=734504 and 2013=735235 
data.timestamps= data_7days.timestamps(1:end-5,:); %Enter the time stamps (Unix format); column vector
data.values= (data_7days.values(1:end-5,[3,7]));%Enter your dataset here; each column is a dataset; missing data -> NaN
data.labels={'Elongation','Temp.'};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% C - Model structure 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Components reference numbers
% 11: Local level
% 12: Local trend
% 13: Local acceleration
% 21: Local level compatible with local trend
% 22: Local level compatible with local acceleration
% 23: Local trend compatible with local acceleration
% 31: Periodic
% 41: Autoregressive
% 51: kernel regression
% 61: Level Intervention

% Model components
% Model 1
model.components.block{1}={[23 51] [11 51] };
model.components.block{2}={[13 51] [11 51] };


% Model component constrains | Take the same  parameter as model class #1
 model.components.const{2}={[0 1] [1 1]};
% Model inter-components dependence | {[components form dataset_i depends on components form dataset_j]_i,[...]}
 model.components.ic={[2],[]};
 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% D - Model parameters 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
model.param_properties={
    % #1             #2 .       #3       #4      #5                  #6          #7      #8      #9              #10
    % Param name     Block name Model    Obs     Bound               Prior       Mean    Std     Values          Ref
	'\sigma_w'  ,	 'TcA',		'1',	 '1',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 1E-20   ,  	 1  %#1
	'\ell'      ,	 'KR',		'1',	 '1',	 [ 0    , Inf  ],	 'normal',	 0 ,	 1E+06,	 1.0907  ,  	 2  %#2
	'p'         ,	 'KR',		'1',	 '1',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 365.24  ,  	 3  %#3
	'\sigma_w'  ,	 'KR',		'1',	 '1',	 [ 0    , Inf  ],	 'normal',	 0 ,	 1E+06,	 0.01666 ,  	 4  %#4
	'\sigma_hw' ,	 'KR',		'1',	 '1',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 0       ,  	 5  %#5
	'\sigma_v'  ,	 '',		'1',	 '1',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 0.02    ,  	 6  %#6
	'\sigma_w'  ,	 'LL',		'1',	 '2',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 0       ,  	 7  %#7
	'\ell'      ,	 'KR',		'1',	 '2',	 [ 0    , Inf  ],	 'normal',	 0 ,	 1E+06,	 0.66775 ,  	 8  %#8
	'p'         ,	 'KR',		'1',	 '2',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 365.24  ,  	 9  %#9
	'\sigma_w'  ,	 'KR',		'1',	 '2',	 [ 0    , Inf  ],	 'normal',	 0 ,	 1E+06,	 2.7948  ,  	 10 %#10
	'\sigma_hw' ,	 'KR',		'1',	 '2',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 0       ,  	 11 %#11
	'\sigma_v'  ,	 '',		'1',	 '2',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 0.25    ,  	 12 %#12
	'\phi'      ,	 '1|2(KR)', '1',	 '2',	 [ -Inf , Inf  ],	 'normal',	 0 ,	 1E+06,	 0.035696,  	 13 %#13
	'\sigma_w'  ,	 'LA',		'2',	 '1',	 [ 0    , Inf  ],	 'normal',	 0 ,	 1E+06,	 1E-5    ,  	 14 %#14
	'\sigma_v'  ,	 '',		'2',	 '1',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 0.02    ,  	 6  %#15
	'\sigma_v'  ,	 '',		'2',	 '2',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 0.25    ,  	 12 %#16
	'\sigma_w'  ,	 'TcA',		'12',	 '1',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 1E-5    ,  	 14 %#17
	'\sigma_w'  ,	 'LL',		'12',	 '2',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 0       ,  	 18 %#18
	'\sigma_w'  ,	 'LA',		'21',	 '1',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 1E-20   ,  	 19 %#19
	'Z(11)'     ,	 '',		'11',	 '',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 0.998   ,  	 20 %#20
	'Z(22)'     ,	 '',		'22',	 '',	 [ NaN  , NaN  ],	 'normal',	 0 ,	 1E+06,	 0.998   ,  	 21 %#21
    };