%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                    OpenBDLM configuration file                          %
%          Autogenerated by OpenBDLM on 19-Feb-2019 22:35:54              %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% A - Project name
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
misc.ProjectName='Example_TRAFFIC_optim';

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% B - Data
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
dat=load('DATA_Example_TRAFFIC_optim.mat'); 
data.values=dat.values;
data.timestamps=dat.timestamps;
data.labels={'TrafficLoad'};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% C - Model structure 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Components reference numbers
% 11: Local level
% 12: Local trend
% 13: Local acceleration
% 21: Local level compatible with local trend
% 22: Local level compatible with local acceleration
% 23: Local trend compatible with local acceleration
% 31: Periodic
% 41: Autoregressive
% 51: Kernel regression
% 61: Level Intervention

% Model components
% Model 1
model.components.block{1}={[11 51 41 ] };

% Model component constrains | Take the same  parameter as model class #1
 
% Model inter-components dependence | {[components form dataset_i depends on components from  dataset_j]_i,[...]}
model.components.ic={[ ] };


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% D - Model parameters 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
model.param_properties={
     % #1           #2             #3      #4    #5               #6           #7       #8              #9              #10
     % Param name   Block name     Model   Obs   Bound            Prior        Mean     Std             Values          Ref
     '\sigma_w',   'LL',           '1',   '1',   [NaN  NaN  ],    'N/A',       NaN,     NaN,            0,              1      %#1   
     '\ell',       'KR',           '1',   '1',   [0  Inf    ],    'N/A',       NaN,     NaN,            0.05249,        2      %#2   
     'p',          'KR',           '1',   '1',   [NaN  NaN  ],    'N/A',       NaN,     NaN,            7,              3      %#3   
     '\sigma_w',   'KR',           '1',   '1',   [0  Inf    ],    'N/A',       NaN,     NaN,            2.1422e-05,     4      %#4   
     '\sigma_hw',  'KR',           '1',   '1',   [NaN  NaN  ],    'N/A',       NaN,     NaN,            0,              5      %#5   
     '\phi',       'AR',           '1',   '1',   [0  1      ],    'N/A',       NaN,     NaN,            0.81701,        6      %#6   
     '\sigma_w',   'AR',           '1',   '1',   [0  Inf    ],    'N/A',       NaN,     NaN,            0.30091,        7      %#7   
     '\sigma_v',   '',             '1',   '1',   [0  Inf    ],    'N/A',       NaN,     NaN,            4.6031e-05,     8      %#8   
};

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% E - Initial states values 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Initial hidden states mean for model 1:
model.initX{ 1 }=[	3.11  	0     	-1.72 	-1.87 	-2.77 	-2.76 	-2.9  	-2.83 	-2.86 	-3    	-2.51 	-2.72 	-1.81 	-1.99 	-2    	-1.84 	-2.77 	-0.86 	-3.51 	-1.99 	-3.17 	-1.99 	-4.35 	0.0119	-6.79 	7.13  	2     	4.36  	4.79  	3.11  	6.15  	-0.155	2.1   	-4.01 	-1.33 	-1.29 	-4.23 	-0.179	-5.52 	3.38  	5.39  	2.55  	6.99  	1.32  	7.13  	1.29  	1.54  	-2.28 	-3.24 	0.0582	-4.28 	-1.58 	-3.43 	-1.74 	8.4   	0.158 	7.22  	1.78  	7.79  	1.27  	2.06  	-0.808	-3.85 	-0.341	-3.13 	-3.29 	-0.68 	-5.23 	7.86  	0.884 	8.2   	2.93  	4.87  	5.67  	-0.47 	1.63  	-4.45 	-1.1  	-1.74 	-4.3  	0.00493	-6.04 	5.15  	4.4   	4.44  	4.92  	4.11  	4.69  	1.33  	-0.189	-2.5  	-2.85 	-1.11 	-3.98 	-1.61 	-3.74 	-0.772	-1.52 	1.1   	-1.6  	-0.426	-2.2  	-0.126]';

% Initial hidden states variance for model 1: 
model.initV{ 1 }=diag([ 	0.0828	8.19  	0.459 	0.436 	0.434 	0.432 	0.431 	0.431 	0.431 	0.431 	0.431 	0.431 	0.431 	0.431 	0.431 	0.432 	0.433 	0.436 	0.444 	0.46  	0.469 	0.472 	0.473 	0.473 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.474 	0.473 	0.473 	0.471 	0.468 	0.182  ]);

% Initial probability for model 1
model.initS{1}=[1     ];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% F - Options 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
misc.options.NaNThreshold=100;
misc.options.Tolerance=1e-06;
misc.options.trainingPeriod=[1  14];
misc.options.isParallel=true;
misc.options.isMute=false;
misc.options.isMAP=false;
misc.options.maxTime=60;
misc.options.maxIterations=100;
misc.options.isLaplaceApprox=false;
misc.options.isPredCap=false;
misc.options.NRLevelsLambdaRef=4;
misc.options.NRTerminationTolerance=1e-07;
misc.options.maxEpochs=50;
misc.options.SplitPercent=30;
misc.options.MiniBatchSizePercent=20;
misc.options.SGTerminationTolerance=95;
misc.options.Optimizer='MMT';
misc.options.MethodStateEstimation='kalman';
misc.options.MaxSizeEstimation=100;
misc.options.DataPercent=100;
misc.options.KRNumberControlPoints=100;
misc.options.Seed=12345;
misc.options.isPlotEstimations=true;
misc.options.FigurePosition=[100   100  1300   270];
misc.options.isSecondaryPlot=false;
misc.options.Subsample=1;
misc.options.Linewidth=1;
misc.options.ndivx=4;
misc.options.ndivy=3;
misc.options.Xaxis_lag=0;
misc.options.isExportTEX=false;
misc.options.isExportPNG=false;
misc.options.isExportPDF=false;
