set(gcf,'Units','inches','Position',[0.5 0.5 5.5 3.5],'PaperPositionMode','auto');
% yticks([0,5,10,15])
% xticks([1,5,10,15])
% title('Structure: 16948, Poutre Element: 1')
% xtickangle(45)
% grid on
figurename='CB3_2010_2013_v1';
set(gcf,'Color',[1 1 1])
% opts=['scaled y ticks = false,',...
%     'scaled x ticks = false,,',...
%     'x label style={font=\Huge},',...
%     'y label style={font=\Huge},',...
%     'z tick label style={/pgf/number format/.cd, fixed, fixed zerofill,precision=2},',...
%     'legend style={font=\Large},',...
%     'title style={font=\huge},',...
%     'mark size=5',...
%     ];
matlab2tikz('figurehandle',gcf,'filename',['ICOLD_figures_tikz/' figurename '.tex'] ,'standalone', true,'showInfo', false);%,'extraTikzpictureOptions','font=\huge','extraaxisoptions',opts);
% matlab2tikz('figurehandle',gcf,'filename',['figures_tikz/' figurename '_1.tex']);

%%
% figure('Units','inches','Position',[0.5 0.5 4 2],'PaperPositionMode','auto');
% set(gca,'Units','normalized','YTick',-1.5:.5:1.5,'XTick',0:t(end)/4:t(end),'Position',[.15 .2 .75 .7],... ?FontUnits?,?points?,... ?FontWeight?,?normal?,... ?FontSize?,9,... ?FontName?,?Times?)